### ISSUE TITLE
Some questions about the model

### ISSUE THREAD

**Issue by phdsea** [crocodilegogogo/If-ConvTransformer#1]
Hello, could you please tell me the model I should use when using the code?Whether I need to train a model by myself ? I tried to train but the resyults is not so good as yours.Thank you !

**Comment by crocodilegogogo** [comment]
Hi, I have provided some models for testing. Some errors occured when running the code? I don't understand your problem. You can use 'If_ConvTransformer_torch' model for the smartphone-based datasets, and use 'If_ConvTransformer_w_torch' model for the wearable device-based datasets, as the paper has mentioned.

**Comment by phdsea** [comment]
Sorry, I couldn't find the model you mentioned in your project. Does the model you mentioned refer to the python file If_ConvTransformer_torch. py?

**Comment by crocodilegogogo** [comment]
Please see the two models in src/classifiers file. I did delete the '.pkl' file used for testing, so you can train one first before testing. I think the experimental results should be very close to the results given in the article, since we adopt the averaged results of three times.

**Comment by phdsea** [comment]
I did try to train a model before , but the best result is about 30% among 30 subjects.I don't know where the problem is. Is the current code complete? Because I saw you at the end of the repository saying that you would update a more complete version

**Comment by crocodilegogogo** [comment]
Yes, the current code is complete. If the result is such unsatisfactory, I suggest to check the training process carefully. I said the more complete version, which is an extension of the IMWUT conference version, the code can be found here: https://github.com/crocodilegogogo/TSF-Under-Review. Still under review. Hope to help.
