### ISSUE TITLE
Can't download the clean_opp.csv file of opportunity dataset

### ISSUE THREAD

**Issue by Anakin2555** [crocodilegogogo/If-ConvTransformer#2]
The storage of git lfs is full.  Git Error: batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

**Comment by crocodilegogogo** [comment]
Thanks for your reminder. I may not update the git lfs storage anylonger. However, if you need the clean_opp.csv file, please leave your email, and I will send you a copy. Or, please check the https://github.com/crocodilegogogo/TSF-Under-Review repository, which includes the code for generating the clean_opp.csv file. Sorry for replying late (I was busy recently).

**Comment by Anakin2555** [comment]
> Thanks for your reminder. I may not update the git lfs storage anylonger. However, if you need the clean_opp.csv file, please leave your email, and I will send you a copy. Or, please check the https://github.com/crocodilegogogo/TSF-Under-Review repository, which includes the code for generating the clean_opp.csv file. Sorry for replying late (I was busy recently).

Thanks for the reply, I have found the code for generating the file in the new repository. Issue solved!!!
